/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CrmRouteImport } from './routes/crm'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CrmIndexRouteImport } from './routes/crm.index'
import { Route as CrmVisaRouteImport } from './routes/crm.visa'
import { Route as CrmVendorsRouteImport } from './routes/crm.vendors'
import { Route as CrmTasksRouteImport } from './routes/crm.tasks'
import { Route as CrmSettingsRouteImport } from './routes/crm.settings'
import { Route as CrmReportsRouteImport } from './routes/crm.reports'
import { Route as CrmPaymentsRouteImport } from './routes/crm.payments'
import { Route as CrmPackagesRouteImport } from './routes/crm.packages'
import { Route as CrmLeadsRouteImport } from './routes/crm.leads'
import { Route as CrmEmployeesRouteImport } from './routes/crm.employees'
import { Route as CrmDocumentsRouteImport } from './routes/crm.documents'
import { Route as CrmCustomersRouteImport } from './routes/crm.customers'
import { Route as CrmBookingsRouteImport } from './routes/crm.bookings'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmRoute = CrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmIndexRoute = CrmIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CrmRoute,
} as any)
const CrmVisaRoute = CrmVisaRouteImport.update({
  id: '/visa',
  path: '/visa',
  getParentRoute: () => CrmRoute,
} as any)
const CrmVendorsRoute = CrmVendorsRouteImport.update({
  id: '/vendors',
  path: '/vendors',
  getParentRoute: () => CrmRoute,
} as any)
const CrmTasksRoute = CrmTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => CrmRoute,
} as any)
const CrmSettingsRoute = CrmSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => CrmRoute,
} as any)
const CrmReportsRoute = CrmReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => CrmRoute,
} as any)
const CrmPaymentsRoute = CrmPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => CrmRoute,
} as any)
const CrmPackagesRoute = CrmPackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => CrmRoute,
} as any)
const CrmLeadsRoute = CrmLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => CrmRoute,
} as any)
const CrmEmployeesRoute = CrmEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => CrmRoute,
} as any)
const CrmDocumentsRoute = CrmDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => CrmRoute,
} as any)
const CrmCustomersRoute = CrmCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => CrmRoute,
} as any)
const CrmBookingsRoute = CrmBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => CrmRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/crm': typeof CrmRouteWithChildren
  '/login': typeof LoginRoute
  '/crm/bookings': typeof CrmBookingsRoute
  '/crm/customers': typeof CrmCustomersRoute
  '/crm/documents': typeof CrmDocumentsRoute
  '/crm/employees': typeof CrmEmployeesRoute
  '/crm/leads': typeof CrmLeadsRoute
  '/crm/packages': typeof CrmPackagesRoute
  '/crm/payments': typeof CrmPaymentsRoute
  '/crm/reports': typeof CrmReportsRoute
  '/crm/settings': typeof CrmSettingsRoute
  '/crm/tasks': typeof CrmTasksRoute
  '/crm/vendors': typeof CrmVendorsRoute
  '/crm/visa': typeof CrmVisaRoute
  '/crm/': typeof CrmIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/crm/bookings': typeof CrmBookingsRoute
  '/crm/customers': typeof CrmCustomersRoute
  '/crm/documents': typeof CrmDocumentsRoute
  '/crm/employees': typeof CrmEmployeesRoute
  '/crm/leads': typeof CrmLeadsRoute
  '/crm/packages': typeof CrmPackagesRoute
  '/crm/payments': typeof CrmPaymentsRoute
  '/crm/reports': typeof CrmReportsRoute
  '/crm/settings': typeof CrmSettingsRoute
  '/crm/tasks': typeof CrmTasksRoute
  '/crm/vendors': typeof CrmVendorsRoute
  '/crm/visa': typeof CrmVisaRoute
  '/crm': typeof CrmIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/crm': typeof CrmRouteWithChildren
  '/login': typeof LoginRoute
  '/crm/bookings': typeof CrmBookingsRoute
  '/crm/customers': typeof CrmCustomersRoute
  '/crm/documents': typeof CrmDocumentsRoute
  '/crm/employees': typeof CrmEmployeesRoute
  '/crm/leads': typeof CrmLeadsRoute
  '/crm/packages': typeof CrmPackagesRoute
  '/crm/payments': typeof CrmPaymentsRoute
  '/crm/reports': typeof CrmReportsRoute
  '/crm/settings': typeof CrmSettingsRoute
  '/crm/tasks': typeof CrmTasksRoute
  '/crm/vendors': typeof CrmVendorsRoute
  '/crm/visa': typeof CrmVisaRoute
  '/crm/': typeof CrmIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/crm'
    | '/login'
    | '/crm/bookings'
    | '/crm/customers'
    | '/crm/documents'
    | '/crm/employees'
    | '/crm/leads'
    | '/crm/packages'
    | '/crm/payments'
    | '/crm/reports'
    | '/crm/settings'
    | '/crm/tasks'
    | '/crm/vendors'
    | '/crm/visa'
    | '/crm/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/crm/bookings'
    | '/crm/customers'
    | '/crm/documents'
    | '/crm/employees'
    | '/crm/leads'
    | '/crm/packages'
    | '/crm/payments'
    | '/crm/reports'
    | '/crm/settings'
    | '/crm/tasks'
    | '/crm/vendors'
    | '/crm/visa'
    | '/crm'
  id:
    | '__root__'
    | '/'
    | '/crm'
    | '/login'
    | '/crm/bookings'
    | '/crm/customers'
    | '/crm/documents'
    | '/crm/employees'
    | '/crm/leads'
    | '/crm/packages'
    | '/crm/payments'
    | '/crm/reports'
    | '/crm/settings'
    | '/crm/tasks'
    | '/crm/vendors'
    | '/crm/visa'
    | '/crm/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CrmRoute: typeof CrmRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm': {
      id: '/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof CrmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm/': {
      id: '/crm/'
      path: '/'
      fullPath: '/crm/'
      preLoaderRoute: typeof CrmIndexRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/visa': {
      id: '/crm/visa'
      path: '/visa'
      fullPath: '/crm/visa'
      preLoaderRoute: typeof CrmVisaRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/vendors': {
      id: '/crm/vendors'
      path: '/vendors'
      fullPath: '/crm/vendors'
      preLoaderRoute: typeof CrmVendorsRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/tasks': {
      id: '/crm/tasks'
      path: '/tasks'
      fullPath: '/crm/tasks'
      preLoaderRoute: typeof CrmTasksRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/settings': {
      id: '/crm/settings'
      path: '/settings'
      fullPath: '/crm/settings'
      preLoaderRoute: typeof CrmSettingsRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/reports': {
      id: '/crm/reports'
      path: '/reports'
      fullPath: '/crm/reports'
      preLoaderRoute: typeof CrmReportsRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/payments': {
      id: '/crm/payments'
      path: '/payments'
      fullPath: '/crm/payments'
      preLoaderRoute: typeof CrmPaymentsRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/packages': {
      id: '/crm/packages'
      path: '/packages'
      fullPath: '/crm/packages'
      preLoaderRoute: typeof CrmPackagesRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/leads': {
      id: '/crm/leads'
      path: '/leads'
      fullPath: '/crm/leads'
      preLoaderRoute: typeof CrmLeadsRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/employees': {
      id: '/crm/employees'
      path: '/employees'
      fullPath: '/crm/employees'
      preLoaderRoute: typeof CrmEmployeesRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/documents': {
      id: '/crm/documents'
      path: '/documents'
      fullPath: '/crm/documents'
      preLoaderRoute: typeof CrmDocumentsRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/customers': {
      id: '/crm/customers'
      path: '/customers'
      fullPath: '/crm/customers'
      preLoaderRoute: typeof CrmCustomersRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/bookings': {
      id: '/crm/bookings'
      path: '/bookings'
      fullPath: '/crm/bookings'
      preLoaderRoute: typeof CrmBookingsRouteImport
      parentRoute: typeof CrmRoute
    }
  }
}

interface CrmRouteChildren {
  CrmBookingsRoute: typeof CrmBookingsRoute
  CrmCustomersRoute: typeof CrmCustomersRoute
  CrmDocumentsRoute: typeof CrmDocumentsRoute
  CrmEmployeesRoute: typeof CrmEmployeesRoute
  CrmLeadsRoute: typeof CrmLeadsRoute
  CrmPackagesRoute: typeof CrmPackagesRoute
  CrmPaymentsRoute: typeof CrmPaymentsRoute
  CrmReportsRoute: typeof CrmReportsRoute
  CrmSettingsRoute: typeof CrmSettingsRoute
  CrmTasksRoute: typeof CrmTasksRoute
  CrmVendorsRoute: typeof CrmVendorsRoute
  CrmVisaRoute: typeof CrmVisaRoute
  CrmIndexRoute: typeof CrmIndexRoute
}

const CrmRouteChildren: CrmRouteChildren = {
  CrmBookingsRoute: CrmBookingsRoute,
  CrmCustomersRoute: CrmCustomersRoute,
  CrmDocumentsRoute: CrmDocumentsRoute,
  CrmEmployeesRoute: CrmEmployeesRoute,
  CrmLeadsRoute: CrmLeadsRoute,
  CrmPackagesRoute: CrmPackagesRoute,
  CrmPaymentsRoute: CrmPaymentsRoute,
  CrmReportsRoute: CrmReportsRoute,
  CrmSettingsRoute: CrmSettingsRoute,
  CrmTasksRoute: CrmTasksRoute,
  CrmVendorsRoute: CrmVendorsRoute,
  CrmVisaRoute: CrmVisaRoute,
  CrmIndexRoute: CrmIndexRoute,
}

const CrmRouteWithChildren = CrmRoute._addFileChildren(CrmRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CrmRoute: CrmRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
