-- Add new fields to the customers table
ALTER TABLE public.customers
ADD COLUMN IF NOT EXISTS company TEXT,
ADD COLUMN IF NOT EXISTS city TEXT,
ADD COLUMN IF NOT EXISTS reference TEXT,
ADD COLUMN IF NOT EXISTS source TEXT,
ADD COLUMN IF NOT EXISTS status TEXT,
ADD COLUMN IF NOT EXISTS "assignedTo" TEXT,
ADD COLUMN IF NOT EXISTS dob TEXT,
ADD COLUMN IF NOT EXISTS "dateOfAnniversary" TEXT,
ADD COLUMN IF NOT EXISTS gst TEXT;
